# ------------------
# config.yaml to store options for streamlistener.py
#
# SCHEME:
#
# mongodb:
#     host: <hostname>
#     port: <portnumber>
#     db: <name_of_db>
#
# collections:
#     <collection_name>:    # Used as collection name in Mongo.
#         keywords:
#            - <words to listen for>   # Filter Twitter stream for these
#            - <more words to listen for>
#         currencycode:
#            - BTC
#     <next_collection_name>:
#     [...]
#
# -------------------

mongodb:
    host: crypto-mongo
    port: 27017
    db:   cryptocrawl

collections:
    generalcrypto:
        keywords:
            - blockchain
            - crypto
            - altcoins
            - altcoin
    bitcoin:
        keywords:
            - bitcoin
            - btc
        currencycode:
            - BTC
    ethereum:
        keywords:
            - ethereum
            - eth
        currencycode:
            - ETH
    iota:
        keywords:
            - iota
            - iot
        currencycode:
            - IOT
    trumpp:
        keywords:
            - trumpp
