collections:
    collection_name:
        - word_1_to_listen_for
        - word_2_to_listen_for
        - word_3_to_listen_for
    bitcoin:
        - bitcoin
        - blockchain
    trumpp:
        - trump        
