collections:
    generalcrypto:
        keywords:
            - blockchain
            - crypto
            - altcoins
            - altcoin
    bitcoin:
        keywords:
            - bitcoin
            - btc
        currencycode:
            - BTC
    ethereum:
        keywords:
            - ethereum
            - eth
        currencycode:
            - ETH
    iota:
        keywords:
            - iota
            - iot
        currencycode:
            - IOT
    trumpp:
        keywords:
            - trump
