version: '3'

networks:
  backend:
    internal: true
  frontend:
    internal: false

services:
  crypto-mongo:
    image: mongo:jessie
    volumes:
      - /data/mongodb:/data/db:rw
    networks:
      - backend

  crypto-price-listener:
    build:
      context: ./miniconda3-prices
    networks:
      - backend
      - frontend
    depends_on:
      - crypto-mongo

  crypto-jupyter:
    volumes:
      - /data/notebooks:/home/jovyan/work
    networks:
      - backend
      - frontend
    ports:
      - 8888:8888
    build:
      context: ./jupyter
    depends_on:
      - crypto-mongo
    entrypoint:
      - start-notebook.sh
      - --NotebookApp.password='sha1:f6a0093ff7ca:be25a6064ba30e37265b0f800cbb925c636cc4fe'

  twitter-listener:
    networks:
      - backend
      - frontend
    build:
      context: ./miniconda3-twitter
      args:
        credsfile: ./credentials.yaml
    depends_on:
      - crypto-mongo

  crypto-dash:
    networks:
      - backend
      - frontend
    build:
      context: ./miniconda3-dash
    ports:
      - 8050:8050
    depends_on:
      - crypto-mongo

  crypto-topics:
    networks:
      - backend
    build:
      context: ./miniconda3-topics
    ports:
      - 5000:5000
    depends_on:
      - crypto-mongo
