version: '1'

networks:
  backend:
    internal: true
  frontend:
    internal: false

services:
  crypto-mongo:
    image: mongo:jessie
    volumes:
      - /data/mongodb:/data/db:rw
    networks:
      - backend

  crypto-price-listener:
    build:
      context: ./miniconda3-prices
    networks:
      - backend

  crypto-jupyter:
    volumes:
      - /data/notebooks:/home/jovyan/work
    networks:
      - backend
      - frontend
    ports:
      - 8888:8888
    build:
      context: ./jupyter

  twitter-listener:
    networks:
      - backend
    build:
      context: ./miniconda3-twitter
      args:
        credsfile: ./credentials.yaml

  crypto-dash:
    networks:
      - backend
      - frontend
    build:
      context: ./miniconda3-dash
    ports:
      - 8050:8050

  crypto-topics:
    networks:
      - backend
    build:
      context: ./miniconda3-topics
    ports:
      - 5000:5000
